 # This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: DeepPhe/DeepPhe-Release
          ref: 'xn0.5.0'
          path: 'DeepPhe'

      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
  


      - name: Build with Maven
        run: |
          cd DeepPhe
          ls -la
          cd dphe-onto-db
          mvn --batch-mode clean install -U -DskipTests
          cd ..
          cd dphe-neo4j
          mvn --batch-mode clean install -U -DskipTests
          cd ..
          cd dphe-neo4j-plugin
          mvn --batch-mode clean install -U -DskipTests
          cd ..
          cd dphe-core
          mvn --batch-mode clean install -U -DskipTests
          cd ..
          cd dphe-stream
          mvn --batch-mode clean install -U -DskipTests
          cd ..
          cd dphe-cli
          mvn --batch-mode clean install -U -DskipTests
          cd ..
          mkdir zips

      - uses: vimtor/action-zip@v1
        with:
          files: DeepPhe/dphe-cli/target/deepphe-0.4.0-bin/deepphe-0.4.0/bin/ 
          dest: zips/DeepPhe-bin.zip
          recursive: true

      - uses: vimtor/action-zip@v1   
        with:
          files: DeepPhe/dphe-cli/target/deepphe-0.4.0-bin/deepphe-0.4.0/lib/ 
          dest: zips/DeepPhe-lib.zip
          recursive: true
          
      - uses: vimtor/action-zip@v1   
        with:
          files: DeepPhe/dphe-cli/target/deepphe-0.4.0-bin/deepphe-0.4.0/resources/ 
          dest: zips/DeepPhe-resources.zip
          recursive: true
        
      - uses: vimtor/action-zip@v1   
        with:
          files: DeepPhe/dphe-neo4j-plugin/target/deepphe-neo4j-plugin-0.4.0.jar 
          dest: zips/DeepPhe-neo4j.zip
          recursive: true
          
      - name: Upload Release Asset
        id: upload-resources
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zips/DeepPhe-resources.zip
          asset_name: DeepPhe-resources.zip
          tag: 'refs/heads/main'
          overwrite: true
          
      - name: Upload Release Asset
        id: upload-lib
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zips/DeepPhe-lib.zip
          asset_name: DeepPhe-lib.zip
          tag: 'refs/heads/main'
          overwrite: true
          
      - name: Upload Release Asset
        id: upload-bin
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zips/DeepPhe-bin.zip
          asset_name: DeepPhe-bin.zip
          tag: 'refs/heads/main'
          overwrite: true
          
      - name: Upload Release Asset
        id: upload-neo4j
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zips/DeepPhe-neo4j.zip
          asset_name: DeepPhe-neo4j.zip
          tag: 'refs/heads/main'
          overwrite: true

     
