name: Testing
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: DeepPhe/DeepPhe-Release
          ref: 'xn0.5.9'
          path: 'DeepPhe'

      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
  


      - name: Build with Maven
        run: |
          cd DeepPhe
          cd dphe-onto-db
          (mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "dphe_onto_db_version=(mvn -q -Dexec.executable=echo -Dexec.args='\$\{project.version\}' --non-recursive exec:exec)" >> $GITHUB_ENV
          echo "The version is ${{ env.dphe_onto_db_version }}" 

          
          
      
