# This is a basic workflow to help you get started with Actions

name: Make New Script Zips

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Build with Maven
        run: mkdir zips
          
      - uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: DeepPhe/DeepPhe-startup-scripts
          ref: 'main'
          path: 'scripts'

      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
  
      - uses: vimtor/action-zip@v1
        with:
          files: scripts/DeepPhe-unix-scripts
          dest: scripts/DeepPhe-unix-scripts.zip
          
      - uses: vimtor/action-zip@v1
        with:
          files: scripts/DeepPhe-win-scripts
          dest: scripts/DeepPhe-win-scripts.zip
         
      - uses: vimtor/action-zip@v1
        with:
          files: scripts/DeepPhe-neo4j-conf
          dest: scripts/DeepPhe-neo4j-conf.zip
 
      - name: Upload Release Asset
        id: upload-unix-scripts
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: scripts/DeepPhe-unix-scripts.zip
          asset_name: DeepPhe-unix-scripts.zip
          tag: 'refs/heads/main'
          overwrite: true
          
      - name: Upload Release Asset
        id: upload-win-scripts
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: scripts/DeepPhe-win-scripts.zip
          asset_name: DeepPhe-win-scripts.zip
          tag: 'refs/heads/main'
          overwrite: true

      - name: Upload Release Asset
        id: upload-neo4j-conf
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: scripts/DeepPhe-neo4j-conf.zip
          asset_name: DeepPhe-neo4j-conf.zip
          tag: 'refs/heads/main'
          overwrite: true

